module.exports = {
  // Configuración del ticket
  ticketName: "ticket-",
  ticketDescription: "🌿 Ticket abierto por",
  ticketCreate: "✅ Tu ticket ha sido creado",
  ticketAlreadyExist: "Lo siento, pero ya tienes un ticket abierto.",
  ticketNoPermissions: "Lo siento, pero no tienes permiso para hacer esto.",
  ticketError: "Algo salió mal, intenta de nuevo más tarde.",
  ticketMessageTitle: "Bienvenido, gracias por abrir un ticket.",
  ticketMessageDescription:
    "Un miembro de nuestro equipo de moderación se encargará pronto de tu solicitud. Gracias por esperar con calma y buen humor.",
  ticketClose: "Cerrar",
  ticketCloseEmoji: "📪",
  ticketLock: "Bloquear",
  ticketLockEmoji: "🔒",
  ticketUnlock: "Desbloquear",
  ticketUnlockEmoji: "🔓",
  ticketClaim: "Reclamar",
  ticketClaimEmoji: "👋",
  ticketManage: "Miembros",
  ticketManageEmoji: "➕",
  ticketManageMenuTitle: "Elige un miembro.",
  ticketManageMenuEmoji: "❔",
  ticketCloseTitle: "El ticket se está cerrando en este momento...",
  ticketCloseDescription: "El ticket se cerrará en 5 segundos.",
  ticketSuccessLocked: "El ticket se bloqueó correctamente.",
  ticketAlreadyLocked: "Este ticket ya está bloqueado.",
  ticketSuccessUnlocked: "El ticket se desbloqueó correctamente.",
  ticketAlreadyUnlocked: "Este ticket ya está desbloqueado.",
  ticketSuccessClaim: "El ticket fue reclamado con éxito por",
  ticketAlreadyClaim: "Este ticket ya fue reclamado por",
  ticketDescriptionClaim: ", fue reclamado por",
  ticketTranscriptMember: "Miembro:",
  ticketTranscriptTicket: "Ticket:",
  ticketTranscriptClaimed: "Reclamado:",
  ticketTranscriptModerator: "Moderador:",
  ticketTranscriptTime: "Tiempo:",
  ticketMemberAdd: "se ha agregado al ticket.",
  ticketMemberRemove: "se ha eliminado del ticket.",
};
